/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

use std::sync::atomic::{AtomicUsize, Ordering};

use camino::{Utf8Path, Utf8PathBuf};
use syn::{ext::IdentExt, Ident};
use uniffi_meta::{Metadata, MetadataGroup};

use crate::{
    attrs::{
        extract_docstring, EnumAttributes, FunctionAttributes, ImplAttributes, ObjectAttributes,
        RecordAttributes, TraitAttributes,
    },
    files::{read_to_string, FileId},
    macros, parse_use,
    paths::LookupCache,
    CompileEnv, Enum, Error,
    ErrorKind::*,
    Function, Impl, Ir, Item, Object, RPath, Record, Result, Trait, Visibility,
};

#[derive(Debug)]
pub struct Module {
    pub source: FileId,
    pub vis: Visibility,
    pub crate_root: Utf8PathBuf,
    // Names of all ancestor modules, excluding the crate root, plus this module.
    //
    // This is used to determine child module paths
    pub module_names: Vec<String>,
    pub ident: Ident,
    pub docstring: Option<String>,
    pub items: Vec<Item>,
    pub id: usize,
    pub udl_name: Option<String>,
    pub metadata_from_udl: Vec<uniffi_meta::Metadata>,
}

impl Module {
    pub fn new_crate_root(ident: Ident, file_path: &Utf8Path, env: &CompileEnv) -> Result<Self> {
        let crate_root = file_path
            .parent()
            .ok_or_else(|| Error::new_without_location(InvalidPath(file_path.to_path_buf())))?
            .to_path_buf();
        let (file_id, content) = read_to_string(file_path)?;
        let file = parse_file(file_id, content)?;
        let mut module = Self::empty(ident, file_id, Visibility::Public, vec![], crate_root)?;
        module.add_items(file.attrs, file.items, env)?;
        Ok(module)
    }

    pub fn new_child(
        &self,
        source: FileId,
        ident: Ident,
        vis: Visibility,
        crate_root: Utf8PathBuf,
        attrs: Vec<syn::Attribute>,
        items: Vec<syn::Item>,
        env: &CompileEnv,
    ) -> Result<Self> {
        let mut module_names = self.module_names.clone();
        module_names.push(ident.to_string());
        let mut module = Self::empty(ident, source, vis, module_names, crate_root)?;
        module.add_items(attrs, items, env)?;
        Ok(module)
    }

    pub fn empty(
        ident: Ident,
        source: FileId,
        vis: Visibility,
        module_names: Vec<String>,
        crate_root: Utf8PathBuf,
    ) -> Result<Self> {
        static ID_GENERATOR: AtomicUsize = AtomicUsize::new(0);

        Ok(Self {
            source,
            vis,
            crate_root,
            module_names,
            ident,
            docstring: None,
            items: vec![],
            id: ID_GENERATOR.fetch_add(1, Ordering::Relaxed),
            udl_name: None,
            metadata_from_udl: vec![],
        })
    }

    fn child_module_path(&self, ident: &Ident) -> Option<Utf8PathBuf> {
        let mut dir = self.crate_root.clone();
        for name in self.module_names.iter() {
            dir.push(name);
        }
        let candidates = [
            dir.join(format!("{ident}.rs")),
            dir.join(format!("{ident}/mod.rs")),
        ];
        candidates.into_iter().find(|p| p.exists())
    }

    fn add_items(
        &mut self,
        attrs: Vec<syn::Attribute>,
        syn_items: Vec<syn::Item>,
        env: &CompileEnv,
    ) -> Result<()> {
        // Ignore errors in `extract_docstring`, maybe the module is using a macro or something to
        // generate the docstring.  This is only needed for modules, since we parse every all
        // of them unlike types which are only parsed if they have a UniFFI derive.
        for a in attrs.iter().filter(|a| a.path().is_ident("doc")) {
            extract_docstring(&mut self.docstring, &a.meta);
        }
        for item in syn_items {
            match item {
                syn::Item::Mod(submod)
                    if env
                        .should_parse_module(&submod.attrs)
                        .map_err(|e| Error::new_syn(self.source, e))? =>
                {
                    let ident = submod.ident.clone();
                    match submod.content {
                        None => {
                            // Ignore missing modules, maybe they're generated by a build.rs
                            // file.
                            if let Some(path) = self.child_module_path(&ident) {
                                let (file_id, content) = read_to_string(&path)?;
                                let file = parse_file(file_id, content)?;
                                self.items.push(Item::Module(self.new_child(
                                    file_id,
                                    ident.clone(),
                                    submod.vis.into(),
                                    self.crate_root.clone(),
                                    file.attrs,
                                    file.items,
                                    env,
                                )?));
                            }
                        }
                        Some((_, items)) => {
                            self.items.push(Item::Module(self.new_child(
                                self.source,
                                ident.clone(),
                                submod.vis.into(),
                                self.crate_root.clone(),
                                submod.attrs,
                                items,
                                env,
                            )?));
                        }
                    }
                }
                item => {
                    self.parse_non_module_item(item, env)
                        .map_err(|e| Error::new_syn(self.source, e))?;
                }
            }
        }
        Ok(())
    }

    fn parse_non_module_item(&mut self, item: syn::Item, env: &CompileEnv) -> syn::Result<()> {
        match item {
            syn::Item::Fn(func) => {
                if let Some(attrs) = FunctionAttributes::parse(env, &func.attrs)? {
                    self.items.push(Item::Fn(Function::parse(attrs, func)?));
                }
            }
            syn::Item::Struct(st) => {
                if let Some(attrs) = RecordAttributes::parse(env, &st.attrs)? {
                    let r = Record::parse(env, attrs, st)?;
                    self.items.push(Item::Record(r));
                } else if let Some(attrs) = ObjectAttributes::parse(env, &st.attrs)? {
                    self.items
                        .push(Item::Object(Object::parse(attrs, st.ident, st.vis)?));
                } else {
                    self.items.push(Item::NonUniffi(st.vis.into(), st.ident));
                }
            }
            syn::Item::Enum(en) => {
                if let Some(attrs) = ObjectAttributes::parse(env, &en.attrs)? {
                    self.items
                        .push(Item::Object(Object::parse(attrs, en.ident, en.vis)?));
                } else if let Some(attrs) = EnumAttributes::parse(env, &en.attrs)? {
                    self.items.push(Item::Enum(Enum::parse(env, attrs, en)?));
                } else {
                    self.items.push(Item::NonUniffi(en.vis.into(), en.ident));
                }
            }
            syn::Item::Trait(tr) => {
                if let Some(attrs) = TraitAttributes::parse(env, &tr.attrs)? {
                    self.items.push(Item::Trait(Trait::parse(env, attrs, tr)?));
                }
            }
            syn::Item::Impl(imp) => {
                if let Some(attrs) = ImplAttributes::parse(env, &imp.attrs)? {
                    self.items.push(Item::Impl(Impl::parse(env, attrs, imp)?));
                }
            }
            syn::Item::Type(ty) => self.items.push(Item::Type(ty)),
            syn::Item::Use(use_) => self.items.extend(parse_use(use_)?),
            syn::Item::Macro(item_macro) => {
                if let Some(udl_name) = macros::parse_include_scaffolding(&item_macro.mac)? {
                    self.udl_name = Some(udl_name.value());
                } else {
                    self.items.push(Item::Macro(item_macro));
                }
            }
            _ => (),
        }
        Ok(())
    }

    pub fn lookup_udl_item(&self, ident: &Ident) -> Option<&Item> {
        let ident = ident.unraw();
        self.items.iter().find(|i| match i {
            Item::Udl(ty) => match ty.name() {
                Some(n) => ident == n,
                None => false,
            },
            _ => false,
        })
    }

    pub fn create_metadata<'ir>(
        &'ir self,
        ir: &'ir Ir,
        cache: &mut LookupCache<'ir>,
        module_path: &mut RPath<'ir>,
        metadata: &mut MetadataGroup,
    ) -> Result<()> {
        for item in self.items.iter() {
            match item {
                Item::Fn(f) => {
                    metadata.items.insert(
                        f.fn_metadata(ir, cache, module_path.append_child(item))?
                            .into(),
                    );
                }
                Item::Record(rec) => {
                    let meta = rec.record_metadata(ir, cache, module_path.append_child(item))?;
                    metadata.items.extend(
                        rec.attrs
                            .utraits
                            .uniffi_trait_method_metadata(
                                &module_path,
                                uniffi_meta::Type::Record {
                                    module_path: meta.module_path.clone(),
                                    name: meta.name.clone(),
                                },
                            )?
                            .into_iter()
                            .map(Metadata::from),
                    );
                    metadata.items.insert(meta.into());
                }
                Item::Enum(en) => {
                    let meta = en.enum_metadata(ir, cache, module_path.append_child(item))?;
                    metadata.items.extend(
                        en.attrs
                            .utraits
                            .uniffi_trait_method_metadata(
                                &module_path,
                                uniffi_meta::Type::Enum {
                                    module_path: meta.module_path.clone(),
                                    name: meta.name.clone(),
                                },
                            )?
                            .into_iter()
                            .map(Metadata::from),
                    );
                    metadata.items.insert(meta.into());
                }
                Item::Object(o) => {
                    let meta = o.obj_metadata(ir, cache, module_path.append_child(item))?;
                    metadata.items.extend(
                        o.attrs
                            .utraits
                            .uniffi_trait_method_metadata(
                                &module_path,
                                uniffi_meta::Type::Object {
                                    module_path: meta.module_path.clone(),
                                    name: meta.name.clone(),
                                    imp: meta.imp,
                                },
                            )?
                            .into_iter()
                            .map(Metadata::from),
                    );
                    metadata.items.insert(meta.into());
                }
                Item::Impl(imp) => {
                    metadata
                        .items
                        .extend(imp.impl_metadata(ir, cache, module_path)?)
                }
                Item::Trait(tr) => {
                    metadata.items.extend(tr.trait_metadata(
                        ir,
                        cache,
                        module_path.append_child(item),
                    )?);
                }
                Item::CustomType(custom_type) => {
                    metadata.items.insert(
                        custom_type
                            .custom_type_metadata(ir, cache, module_path.append_child(item))?
                            .into(),
                    );
                }
                Item::Module(submod) => {
                    module_path.push(item);
                    submod.create_metadata(ir, cache, module_path, metadata)?;
                    module_path.pop();
                }
                _ => (),
            }
        }
        metadata.items.extend(self.metadata_from_udl.clone());
        Ok(())
    }
}

fn parse_file(file_id: FileId, content: &str) -> Result<syn::File> {
    syn::parse_file(content).map_err(|e| Error::new(file_id, e.span(), SynError(e.to_string())))
}
