/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

use std::sync::atomic::{AtomicUsize, Ordering};

use camino::{Utf8Path, Utf8PathBuf};
use syn::Ident;
use uniffi_meta::MetadataGroup;

use crate::{
    attrs::{
        extract_docstring, EnumAttributes, FunctionAttributes, ImplAttributes, ObjectAttributes,
        RecordAttributes, TraitAttributes,
    },
    files::{read_to_string, FileId},
    Enum, Error,
    ErrorKind::*,
    Function, Impl, Item, Object, Record, Result, Trait,
};

#[derive(Debug)]
pub struct Module {
    pub source: FileId,
    pub crate_root: Utf8PathBuf,
    // Names of all ancestor modules, excluding the crate root, plus this module.
    //
    // This is used to determine child module paths
    pub module_names: Vec<String>,
    pub ident: Ident,
    pub docstring: Option<String>,
    pub items: Vec<Item>,
    pub id: usize,
}

impl Module {
    pub fn new_crate_root(ident: Ident, file_path: &Utf8Path) -> Result<Self> {
        let crate_root = file_path
            .parent()
            .ok_or_else(|| Error::new_without_location(InvalidPath(file_path.to_path_buf())))?
            .to_path_buf();
        let (file_id, content) = read_to_string(file_path)?;
        let file = parse_file(file_id, content)?;
        let mut module = Self::empty(ident, file_id, vec![], crate_root)?;
        module.add_items(file.attrs, file.items)?;
        Ok(module)
    }

    pub fn new_child(
        &self,
        source: FileId,
        ident: Ident,
        crate_root: Utf8PathBuf,
        attrs: Vec<syn::Attribute>,
        items: Vec<syn::Item>,
    ) -> Result<Self> {
        let mut module_names = self.module_names.clone();
        module_names.push(ident.to_string());
        let mut module = Self::empty(ident, source, module_names, crate_root)?;
        module.add_items(attrs, items)?;
        Ok(module)
    }

    pub fn empty(
        ident: Ident,
        source: FileId,
        module_names: Vec<String>,
        crate_root: Utf8PathBuf,
    ) -> Result<Self> {
        static ID_GENERATOR: AtomicUsize = AtomicUsize::new(0);

        Ok(Self {
            source,
            crate_root,
            module_names,
            ident,
            docstring: None,
            items: vec![],
            id: ID_GENERATOR.fetch_add(1, Ordering::Relaxed),
        })
    }

    fn child_module_path(&self, ident: &Ident) -> Option<Utf8PathBuf> {
        let mut dir = self.crate_root.clone();
        for name in self.module_names.iter() {
            dir.push(name);
        }
        let candidates = [
            dir.join(format!("{ident}.rs")),
            dir.join(format!("{ident}/mod.rs")),
        ];
        candidates.into_iter().find(|p| p.exists())
    }

    fn add_items(&mut self, attrs: Vec<syn::Attribute>, syn_items: Vec<syn::Item>) -> Result<()> {
        // Ignore errors in `extract_docstring`, maybe the module is using a macro or something to
        // generate the docstring.  This is only needed for modules, since we parse every all
        // of them unlike types which are only parsed if they have a UniFFI derive.
        for a in attrs.iter().filter(|a| a.path().is_ident("doc")) {
            extract_docstring(&mut self.docstring, &a.meta);
        }
        for item in syn_items {
            match item {
                syn::Item::Mod(submod) => {
                    let ident = submod.ident.clone();
                    match submod.content {
                        None => {
                            // Ignore missing modules, maybe they're generated by a build.rs
                            // file.
                            if let Some(path) = self.child_module_path(&ident) {
                                let (file_id, content) = read_to_string(&path)?;
                                let file = parse_file(file_id, content)?;
                                self.items.push(Item::Module(self.new_child(
                                    file_id,
                                    ident.clone(),
                                    self.crate_root.clone(),
                                    file.attrs,
                                    file.items,
                                )?));
                            }
                        }
                        Some((_, items)) => {
                            self.items.push(Item::Module(self.new_child(
                                self.source,
                                ident.clone(),
                                self.crate_root.clone(),
                                submod.attrs,
                                items,
                            )?));
                        }
                    }
                }
                item => {
                    self.parse_non_module_item(item)
                        .map_err(|e| Error::new_syn(self.source, e))?;
                }
            }
        }
        Ok(())
    }

    fn parse_non_module_item(&mut self, item: syn::Item) -> syn::Result<()> {
        match item {
            syn::Item::Fn(func) => {
                if let Some(attrs) = FunctionAttributes::parse(&func.attrs)? {
                    self.items.push(Item::Fn(Function::parse(attrs, func)?));
                }
            }
            syn::Item::Struct(st) => {
                if let Some(attrs) = RecordAttributes::parse(&st.attrs)? {
                    let r = Record::parse(attrs, st)?;
                    self.items.push(Item::Record(r));
                } else if let Some(attrs) = ObjectAttributes::parse(&st.attrs)? {
                    self.items
                        .push(Item::Object(Object::parse(attrs, st.ident)?));
                }
            }
            syn::Item::Enum(en) => {
                if let Some(attrs) = ObjectAttributes::parse(&en.attrs)? {
                    self.items
                        .push(Item::Object(Object::parse(attrs, en.ident)?));
                } else if let Some(attrs) = EnumAttributes::parse(&en.attrs)? {
                    self.items.push(Item::Enum(Enum::parse(attrs, en)?));
                }
            }
            syn::Item::Trait(tr) => {
                if let Some(attrs) = TraitAttributes::parse(&tr.attrs)? {
                    self.items.push(Item::Trait(Trait::parse(attrs, tr)?));
                }
            }
            syn::Item::Impl(imp) => {
                if let Some(attrs) = ImplAttributes::parse(&imp.attrs)? {
                    self.items.push(Item::Impl(Impl::parse(attrs, imp)?));
                }
            }
            syn::Item::Type(ty) => self.items.push(Item::Type(ty)),
            syn::Item::Use(use_) => self.items.push(Item::Use(use_)),
            _ => (),
        }
        Ok(())
    }

    pub fn create_metadata(&self, metadata: &mut MetadataGroup) -> Result<()> {
        for item in self.items.iter() {
            match item {
                Item::Fn(f) => {
                    metadata.items.insert(f.fn_metadata()?.into());
                }
                Item::Record(rec) => {
                    metadata.items.insert(rec.record_metadata()?.into());
                }
                Item::Enum(en) => {
                    metadata.items.insert(en.enum_metadata()?.into());
                }
                Item::Object(o) => {
                    metadata.items.insert(o.obj_metadata()?.into());
                }
                Item::Impl(imp) => metadata.items.extend(imp.impl_metadata()?),
                Item::Trait(tr) => {
                    metadata.items.extend(tr.trait_metadata()?);
                }
                Item::Module(submod) => {
                    submod.create_metadata(metadata)?;
                }
                _ => (),
            }
        }
        Ok(())
    }
}

fn parse_file(file_id: FileId, content: &str) -> Result<syn::File> {
    syn::parse_file(content).map_err(|e| Error::new(file_id, e.span(), SynError(e.to_string())))
}
