[package]
name = "uniffi-example-app"
edition = "2018"
version = "0.1.0"
authors = ["Firefox Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"
publish = false

[lib]
crate-type = ["cdylib"]
name = "uniffi_todolist"

[dependencies]
uniffi_macros = {path = "../../../uniffi_macros"}
uniffi = {path = "../../../uniffi", features=["builtin-bindgen"]}
thiserror = "1.0"

[build-dependencies]
uniffi_build = {path = "../../../uniffi_build", features=["builtin-bindgen"]}
