[files]
extend-exclude = [
	"examples/rondpoint/", # Code is in French
	"weedle2" # https://github.com/mozilla/uniffi-rs/pull/1912#discussion_r1435347116
]

[default.extend-identifiers]
ot = "ot"

[default.extend-words]
inout = "inout"
Sur = "Sur" # Big Sur
