enum Case {
  "snake_case",
  "UpperCamelCase",
  "camelCase",
  "SHOUTY_SNAKE_CASE",
};

namespace naming_conventions {
  snake_case_object snake_case_method(u32 id, Case src);
  CamelCaseObject camelCaseMethod(u32 id, Case src);

  Case get_snake_case();
  Case getCamelCase();
};

dictionary snake_case_object {
  u32 id;
};

dictionary CamelCaseObject {
  u32 id;
};
