namespace rondpoint {
  Dictionnaire copie_dictionnaire(Dictionnaire d);
  Enumeration copie_enumeration(Enumeration e);
  sequence<Enumeration> copie_enumerations(sequence<Enumeration> e);
  record<DOMString, Enumeration> copie_carte(record<DOMString, Enumeration> c);
  boolean switcheroo(boolean b);
};

dictionary minusculeMAJUSCULEDict {
  boolean minusculeMAJUSCULEField;
};

enum minusculeMAJUSCULEEnum {
  "minusculeMAJUSCULEVariant",
};

enum Enumeration {
    "Un",
    "Deux",
    "Trois",
};

dictionary Dictionnaire {
    Enumeration un;
    boolean deux;
    u8 petit_nombre;
    u64 gros_nombre;
};
