namespace rondpoint {
  Dictionnaire copie_dictionnaire(Dictionnaire d);
  Enumeration copie_enumeration(Enumeration e);
  sequence<Enumeration> copie_enumerations(sequence<Enumeration> e);
};

enum Enumeration {
    "Un",
    "Deux",
    "Trois",
};

dictionary Dictionnaire {
    Enumeration un;
    boolean deux;
};
