[Error]
enum ArithmeticError {
  "IntegerOverflow",
};

namespace arithmetic {
  [Throws=ArithmeticError]
  u64 add(u64 a, u64 b);

  [Throws=ArithmeticError]
  u64 sub(u64 a, u64 b);

  boolean equal(u64 a, u64 b);
};
