// Source: Web Bluetooth (https://webbluetoothcg.github.io/web-bluetooth/)
[Exposed=Window, SecureContext]
interface Bluetooth : EventTarget {
  Promise<boolean> getAvailability();
  attribute EventHandler onavailabilitychanged;
  [SameObject]
  readonly attribute BluetoothDevice? referringDevice;
  Promise<sequence<BluetoothDevice>> getDevices();
  Promise<BluetoothDevice> requestDevice(optional RequestDeviceOptions options = {});
};

// Source: Web Bluetooth (https://webbluetoothcg.github.io/web-bluetooth/)
Bluetooth includes BluetoothDeviceEventHandlers;

// Source: Web Bluetooth (https://webbluetoothcg.github.io/web-bluetooth/)
Bluetooth includes CharacteristicEventHandlers;

// Source: Web Bluetooth (https://webbluetoothcg.github.io/web-bluetooth/)
Bluetooth includes ServiceEventHandlers;