// Source: Web Bluetooth (https://webbluetoothcg.github.io/web-bluetooth/)
[Exposed=Window]
interface BluetoothPermissionResult : PermissionStatus {
  attribute FrozenArray<BluetoothDevice> devices;
};