// Source: Web Bluetooth (https://webbluetoothcg.github.io/web-bluetooth/)
dictionary BluetoothManufacturerDataFilterInit : BluetoothDataFilterInit {
  required [EnforceRange] unsigned short companyIdentifier;
};