// Source: Web Bluetooth (https://webbluetoothcg.github.io/web-bluetooth/)
[SecureContext]
interface mixin BluetoothDeviceEventHandlers {
  attribute EventHandler onadvertisementreceived;
  attribute EventHandler ongattserverdisconnected;
};