// Source: Screen Capture (https://www.w3.org/TR/screen-capture/)
[Exposed=Window, SecureContext]
interface CaptureController {
  constructor();
  undefined setFocusBehavior(CaptureStartFocusBehavior focusBehavior);
};