// Source: Web Audio API (https://www.w3.org/TR/webaudio/)
[Exposed=Window]
interface ChannelSplitterNode : AudioNode {
    constructor (BaseAudioContext context, optional ChannelSplitterOptions options = {});
};