// Source: Secure Payment Confirmation (https://www.w3.org/TR/secure-payment-confirmation/)
dictionary CollectedClientPaymentData : CollectedClientData {
    required CollectedClientAdditionalPaymentData payment;
};