// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
dictionary CredentialCreationOptions {
  AbortSignal signal;
};

// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
partial dictionary CredentialCreationOptions {
  PasswordCredentialInit password;
};

// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
partial dictionary CredentialCreationOptions {
  FederatedCredentialInit federated;
};

// Source: Web Authentication: An API for accessing Public Key Credentials - Level (https://www.w3.org/TR/webauthn-3/)
partial dictionary CredentialCreationOptions {
    PublicKeyCredentialCreationOptions      publicKey;
};