// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
[SecureContext]
interface mixin CredentialUserData {
  readonly attribute USVString name;
  readonly attribute USVString iconURL;
};