// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
dictionary CredentialRequestOptions {
  CredentialMediationRequirement mediation = "optional";
  AbortSignal signal;
};

// Source: Federated Credential Management API (https://fedidcg.github.io/FedCM/)
partial dictionary CredentialRequestOptions {
  IdentityCredentialRequestOptions identity;
};

// Source: WebOTP API (https://wicg.github.io/web-otp/)
partial dictionary CredentialRequestOptions {
    OTPCredentialRequestOptions otp;
};

// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
partial dictionary CredentialRequestOptions {
  boolean password = false;
};

// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
partial dictionary CredentialRequestOptions {
  FederatedCredentialRequestOptions federated;
};

// Source: Web Authentication: An API for accessing Public Key Credentials - Level (https://www.w3.org/TR/webauthn-3/)
partial dictionary CredentialRequestOptions {
    PublicKeyCredentialRequestOptions      publicKey;
};