// Source: CSS Animations Level 1 (https://www.w3.org/TR/css-animations-1/)
[Exposed=Window]
interface CSSKeyframeRule : CSSRule {
  attribute CSSOMString keyText;
  [SameObject, PutForwards=cssText] readonly attribute CSSStyleDeclaration style;
};