// Source: CSS Object Model (CSSOM) (https://www.w3.org/TR/cssom-1/)
[Exposed=Window]
interface CSSMarginRule : CSSRule {
  readonly attribute CSSOMString name;
  [SameObject, PutForwards=cssText] readonly attribute CSSStyleDeclaration style;
};