// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
[Exposed=Window]
interface DataTransferItem {
  readonly attribute DOMString kind;
  readonly attribute DOMString type;
  undefined getAsString(FunctionStringCallback? _callback);
  File? getAsFile();
};

// Source: File and Directory Entries API (https://wicg.github.io/entries-api/)
partial interface DataTransferItem {
    FileSystemEntry? webkitGetAsEntry();
};

// Source: File System Access (https://wicg.github.io/file-system-access/)
partial interface DataTransferItem {
    Promise<FileSystemHandle?> getAsFileSystemHandle();
};