// Source: DeviceOrientation Event Specification (https://www.w3.org/TR/orientation-event/)
dictionary DeviceMotionEventAccelerationInit {
    double? x = null;
    double? y = null;
    double? z = null;
};