// Source: DeviceOrientation Event Specification (https://www.w3.org/TR/orientation-event/)
dictionary DeviceOrientationEventInit : EventInit {
    double? alpha = null;
    double? beta = null;
    double? gamma = null;
    boolean absolute = false;
};