// Source: File System Access (https://wicg.github.io/file-system-access/)
dictionary DirectoryPickerOptions {
    DOMString id;
    StartInDirectory startIn;
    FileSystemPermissionMode mode = "read";
};