// Source: Web Animations (https://www.w3.org/TR/web-animations-1/)
dictionary EffectTiming {
    FillMode                           fill = "auto";
    double                             iterationStart = 0.0;
    unrestricted double                iterations = 1.0;
    PlaybackDirection                  direction = "normal";
    DOMString                          easing = "linear";
};

// Source: Web Animations Level 2 (https://drafts.csswg.org/web-animations-2/)
partial dictionary EffectTiming {
    double delay;
    double endDelay;
    double playbackRate = 1.0;
    (unrestricted double or CSSNumericValue or DOMString) duration = "auto";
};