// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
dictionary ErrorEventInit : EventInit {
  DOMString message = "";
  USVString filename = "";
  unsigned long lineno = 0;
  unsigned long colno = 0;
  any error;
};