// Source: EyeDropper API (https://wicg.github.io/eyedropper-api/)
[Exposed=Window, SecureContext]
interface EyeDropper {
    constructor();
    Promise<ColorSelectionResult> open(optional ColorSelectionOptions options = {});
};