// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
[Exposed=Window,
 SecureContext]
interface FederatedCredential : Credential {
  constructor(FederatedCredentialInit data);
  readonly attribute USVString provider;
  readonly attribute DOMString? protocol;
};

// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
FederatedCredential includes CredentialUserData;