// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
dictionary FederatedCredentialRequestOptions {
  sequence<USVString> providers;
  sequence<DOMString> protocols;
};