// Source: File and Directory Entries API (https://wicg.github.io/entries-api/)
[Exposed=Window]
interface FileSystem {
    readonly attribute USVString name;
    readonly attribute FileSystemDirectoryEntry root;
};