// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, DedicatedWorker), SecureContext]
interface GPUComputePassEncoder {
    undefined setPipeline(GPUComputePipeline pipeline);
    undefined dispatchWorkgroups(GPUSize32 workgroupCountX, optional GPUSize32 workgroupCountY = 1, optional GPUSize32 workgroupCountZ = 1);
    undefined dispatchWorkgroupsIndirect(GPUBuffer indirectBuffer, GPUSize64 indirectOffset);

    undefined end();
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUComputePassEncoder includes GPUObjectBase;

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUComputePassEncoder includes GPUCommandsMixin;

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUComputePassEncoder includes GPUDebugCommandsMixin;

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUComputePassEncoder includes GPUBindingCommandsMixin;