// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, DedicatedWorker), SecureContext]
interface GPUCommandBuffer {
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUCommandBuffer includes GPUObjectBase;