// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, DedicatedWorker), SecureContext]
interface GPUExternalTexture {
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUExternalTexture includes GPUObjectBase;