// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, DedicatedWorker), SecureContext]
interface GPUPipelineLayout {
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUPipelineLayout includes GPUObjectBase;