// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, DedicatedWorker), SecureContext, Serializable]
interface GPUPipelineError : DOMException {
    constructor(DOMString message, GPUPipelineErrorInit options);
    readonly attribute GPUPipelineErrorReason reason;
};