// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, DedicatedWorker), SecureContext]
interface GPURenderBundle {
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPURenderBundle includes GPUObjectBase;