// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, DedicatedWorker), SecureContext]
interface GPUShaderModule {
    Promise<GPUCompilationInfo> getCompilationInfo();
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUShaderModule includes GPUObjectBase;