// Source: WebHID API (https://wicg.github.io/webhid/)
dictionary HIDDeviceFilter {
    unsigned long vendorId;
    unsigned short productId;
    unsigned short usagePage;
    unsigned short usage;
};