// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
[Exposed=Window]
interface HTMLMenuElement : HTMLElement {
  [HTMLConstructor] constructor();

  // also has obsolete members
};

// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
partial interface HTMLMenuElement {
  [CEReactions] attribute boolean compact;
};