// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
[Exposed=Window]
interface HTMLHeadingElement : HTMLElement {
  [HTMLConstructor] constructor();

  // also has obsolete members
};

// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
partial interface HTMLHeadingElement {
  [CEReactions] attribute DOMString align;
};