// Source: Federated Credential Management API (https://fedidcg.github.io/FedCM/)
dictionary IdentityProviderBranding {
  USVString background_color;
  USVString color;
  sequence<IdentityProviderIcon> icons;
  USVString name;
};