// Source: requestIdleCallback() (https://www.w3.org/TR/requestidlecallback/)
[Exposed=Window] interface IdleDeadline {
  DOMHighResTimeStamp timeRemaining();
  readonly attribute boolean didTimeout;
};