// Source: Ink API (https://wicg.github.io/ink-enhancement/)
[Exposed=Window]
interface InkPresenter {
    readonly attribute Element? presentationArea;
    readonly attribute unsigned long expectedImprovement;

    undefined updateInkTrailStartPoint(PointerEvent event, InkTrailStyle style);
};