// Source: Intersection Observer (https://www.w3.org/TR/intersection-observer/)
callback IntersectionObserverCallback = undefined (sequence<IntersectionObserverEntry> entries, IntersectionObserver observer);