// Source: CSS Layout API Level 1 (https://www.w3.org/TR/css-layout-api-1/)
[Exposed=LayoutWorklet]
interface IntrinsicSizes {
  readonly attribute double minContentSize;
  readonly attribute double maxContentSize;
};