// Source: Media Capabilities (https://www.w3.org/TR/media-capabilities/)
dictionary MediaCapabilitiesInfo {
  required boolean supported;
  required boolean smooth;
  required boolean powerEfficient;
};