// Source: Media Session Standard (https://www.w3.org/TR/mediasession/)
dictionary MediaMetadataInit {
  DOMString title = "";
  DOMString artist = "";
  DOMString album = "";
  sequence<MediaImage> artwork = [];
};