// Source: Encrypted Media Extensions (https://www.w3.org/TR/encrypted-media/)
dictionary MediaKeyMessageEventInit : EventInit {
             required MediaKeyMessageType messageType;
             required ArrayBuffer         message;
};