// Source: Media Capabilities (https://www.w3.org/TR/media-capabilities/)
dictionary MediaDecodingConfiguration : MediaConfiguration {
  required MediaDecodingType type;
  MediaCapabilitiesKeySystemConfiguration keySystemConfiguration;
};