// Source: Media Session Standard (https://www.w3.org/TR/mediasession/)
dictionary MediaSessionActionDetails {
  required MediaSessionAction action;
  double seekOffset;
  double seekTime;
  boolean fastSeek;
};