// Source: Web Audio API (https://www.w3.org/TR/webaudio/)
[Exposed=Window]
interface MediaStreamTrackAudioSourceNode : AudioNode {
    constructor (AudioContext context, MediaStreamTrackAudioSourceOptions options);
};