// Source: Media Source Extensions™ (https://www.w3.org/TR/media-source-2/)
[Exposed=(Window,DedicatedWorker)]
interface MediaSource : EventTarget {
    constructor();

    [ SameObject, Exposed=DedicatedWorker ]
    readonly              attribute MediaSourceHandle   handle;

    readonly              attribute SourceBufferList    sourceBuffers;
    readonly              attribute SourceBufferList    activeSourceBuffers;
    readonly              attribute ReadyState          readyState;
                          attribute unrestricted double duration;
                          attribute EventHandler        onsourceopen;
                          attribute EventHandler        onsourceended;
                          attribute EventHandler        onsourceclose;
    static readonly       attribute boolean canConstructInDedicatedWorker;
    SourceBuffer          addSourceBuffer (DOMString type);
    undefined             removeSourceBuffer (SourceBuffer sourceBuffer);
    undefined             endOfStream (optional EndOfStreamError error);
    undefined             setLiveSeekableRange (double start, double end);
    undefined             clearLiveSeekableRange ();
    static boolean        isTypeSupported (DOMString type);
};