// Source: WebAssembly JavaScript Interface (https://www.w3.org/TR/wasm-js-api-2/)
[LegacyNamespace=WebAssembly, Exposed=*]
interface Memory {
  constructor(MemoryDescriptor descriptor);
  unsigned long grow([EnforceRange] unsigned long delta);
  readonly attribute ArrayBuffer buffer;
};