// Source: Web MIDI API (https://www.w3.org/TR/webmidi/)
[SecureContext, Exposed=Window]
interface MIDIConnectionEvent : Event {
  constructor(DOMString type, optional MIDIConnectionEventInit eventInitDict = {});
  readonly attribute MIDIPort port;
};