// Source: Media Capture Automation (https://w3c.github.io/mediacapture-automation/)
dictionary MockCapturePromptResultConfiguration {
  MockCapturePromptResult getUserMedia;
  MockCapturePromptResult getDisplayMedia;
};