// Source: WebAssembly JavaScript Interface (https://www.w3.org/TR/wasm-js-api-2/)
dictionary ModuleImportDescriptor {
  required USVString module;
  required USVString name;
  required ImportExportKind kind;
};