// Source: CSS Spatial Navigation Level 1 (https://www.w3.org/TR/css-nav-1/)
dictionary NavigationEventInit : UIEventInit {
    SpatialNavigationDirection dir;
    EventTarget? relatedTarget = null;
};