// Source: Device Memory (https://www.w3.org/TR/device-memory-1/)
[
    SecureContext,
    Exposed=(Window,Worker)
] interface mixin NavigatorDeviceMemory {
    readonly attribute double deviceMemory;
};