// Source: Secure Payment Confirmation (https://www.w3.org/TR/secure-payment-confirmation/)
dictionary PaymentCredentialInstrument {
    required USVString displayName;
    required USVString icon;
    boolean iconMustBeShown = true;
};