// Source: Permissions Policy (https://www.w3.org/TR/permissions-policy-1/)
[Exposed=Window]
interface PermissionsPolicyViolationReportBody : ReportBody {
  readonly attribute DOMString featureId;
  readonly attribute DOMString? sourceFile;
  readonly attribute long? lineNumber;
  readonly attribute long? columnNumber;
  readonly attribute DOMString disposition;
};