// Source: Portals (https://wicg.github.io/portals/)
[Exposed=Window]
interface PortalHost : EventTarget {
    undefined postMessage(any message, optional StructuredSerializeOptions options = {});

    attribute EventHandler onmessage;
    attribute EventHandler onmessageerror;
};