// Source: Compute Pressure Level 1 (https://www.w3.org/TR/compute-pressure/)
[Exposed=(DedicatedWorker,SharedWorker,Window), SecureContext]
interface PressureObserver {
  constructor(PressureUpdateCallback callback, optional PressureObserverOptions options = {});

  Promise<undefined> observe(PressureSource source);
  undefined unobserve(PressureSource source);
  undefined disconnect();
  sequence<PressureRecord> takeRecords();

  [SameObject] static readonly attribute FrozenArray<PressureSource> supportedSources;
};