// Source: Presentation API (https://www.w3.org/TR/presentation-api/)
[SecureContext, Exposed=Window]
interface PresentationAvailability : EventTarget {
  readonly attribute boolean value;

  attribute EventHandler onchange;
};