// Source: Compute Pressure Level 1 (https://www.w3.org/TR/compute-pressure/)
[Exposed=(DedicatedWorker,SharedWorker,Window), SecureContext]
interface PressureRecord {
  readonly attribute PressureSource source;
  readonly attribute PressureState state;
  readonly attribute FrozenArray<PressureFactor> factors;
  readonly attribute DOMHighResTimeStamp time;
  [Default] object toJSON();
};