// Source: DOM Standard (https://dom.spec.whatwg.org/)
[Exposed=Window]
interface ProcessingInstruction : CharacterData {
  readonly attribute DOMString target;
};

// Source: CSS Object Model (CSSOM) (https://www.w3.org/TR/cssom-1/)
ProcessingInstruction includes LinkStyle;