// Source: JS Self-Profiling API (https://wicg.github.io/js-self-profiling/)
dictionary ProfilerFrame {
  required DOMString name;
  unsigned long long resourceId;
  unsigned long long line;
  unsigned long long column;
};