// Source: Service Workers Nightly (https://www.w3.org/TR/service-workers/)
dictionary RegistrationOptions {
  USVString scope;
  WorkerType type = "classic";
  ServiceWorkerUpdateViaCache updateViaCache = "imports";
};