// Source: Orientation Sensor (https://www.w3.org/TR/orientation-sensor/)
[SecureContext, Exposed=Window]
interface RelativeOrientationSensor : OrientationSensor {
  constructor(optional OrientationSensorOptions sensorOptions = {});
};