// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
typedef (CanvasRenderingContext2D or ImageBitmapRenderingContext or WebGLRenderingContext or WebGL2RenderingContext or GPUCanvasContext) RenderingContext;