// Source: Resize Observer (https://www.w3.org/TR/resize-observer-1/)
[Exposed=Window]
interface ResizeObserverSize {
    readonly attribute unrestricted double inlineSize;
    readonly attribute unrestricted double blockSize;
};