// Source: Web Cryptography API (https://www.w3.org/TR/WebCryptoAPI/)
dictionary RsaOtherPrimesInfo {
  // The following fields are defined in Section 6.3.2.7 of JSON Web Algorithms
  DOMString r;
  DOMString d;
  DOMString t;
};