// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
// New enum for video frame types. Will eventually re-use the equivalent defined
// by WebCodecs.
enum RTCEncodedVideoFrameType {
    "empty",
    "key",
    "delta",
};