// Source: Identifiers for WebRTC's Statistics API (https://www.w3.org/TR/webrtc-stats/)
dictionary RTCInboundRtpStreamStats : RTCReceivedRtpStreamStats {
 required DOMString   trackIdentifier;
 required DOMString   kind;
 DOMString            mid;
 DOMString            remoteId;
 unsigned long        framesDecoded;
 unsigned long        keyFramesDecoded;
 unsigned long        framesRendered;
 unsigned long        framesDropped;
 unsigned long        frameWidth;
 unsigned long        frameHeight;
 double               framesPerSecond;
 unsigned long long   qpSum;
 double               totalDecodeTime;
 double               totalInterFrameDelay;
 double               totalSquaredInterFrameDelay;
 unsigned long        pauseCount;
 double               totalPausesDuration;
 unsigned long        freezeCount;
 double               totalFreezesDuration;
 DOMHighResTimeStamp  lastPacketReceivedTimestamp;
 unsigned long long   headerBytesReceived;
 unsigned long long   packetsDiscarded;
 unsigned long long   fecPacketsReceived;
 unsigned long long   fecPacketsDiscarded;
 unsigned long long   bytesReceived;
 unsigned long        nackCount;
 unsigned long        firCount;
 unsigned long        pliCount;
 double               totalProcessingDelay;
 DOMHighResTimeStamp  estimatedPlayoutTimestamp;
 double               jitterBufferDelay;
 double               jitterBufferTargetDelay;
 unsigned long long   jitterBufferEmittedCount;
 double               jitterBufferMinimumDelay;
 unsigned long long   totalSamplesReceived;
 unsigned long long   concealedSamples;
 unsigned long long   silentConcealedSamples;
 unsigned long long   concealmentEvents;
 unsigned long long   insertedSamplesForDeceleration;
 unsigned long long   removedSamplesForAcceleration;
 double               audioLevel;
 double               totalAudioEnergy;
 double               totalSamplesDuration;
 unsigned long        framesReceived;
 DOMString            decoderImplementation;
 DOMString            playoutId;
 boolean              powerEfficientDecoder;
 unsigned long        framesAssembledFromMultiplePackets;
 double               totalAssemblyTime;
};