// Source: WebRTC: Real-Time Communication in Browsers (https://www.w3.org/TR/webrtc/)
dictionary RTCRtpSendParameters : RTCRtpParameters {
  required DOMString transactionId;
  required sequence<RTCRtpEncodingParameters> encodings;
};

// Source: MediaStreamTrack Content Hints (https://www.w3.org/TR/mst-content-hint/)
partial dictionary RTCRtpSendParameters {
 RTCDegradationPreference degradationPreference;
};