// Source: WebRTC: Real-Time Communication in Browsers (https://www.w3.org/TR/webrtc/)
dictionary RTCRtpTransceiverInit {
  RTCRtpTransceiverDirection direction = "sendrecv";
  sequence<MediaStream> streams = [];
  sequence<RTCRtpEncodingParameters> sendEncodings = [];
};