// Source: WebRTC: Real-Time Communication in Browsers (https://www.w3.org/TR/webrtc/)
dictionary RTCStats {
  required DOMHighResTimeStamp timestamp;
  required RTCStatsType type;
  required DOMString id;
};