// Source: Prioritized Task Scheduling (https://wicg.github.io/scheduling-apis/)
[Exposed=(Window, Worker)]
interface Scheduler {
  Promise<any> postTask(SchedulerPostTaskCallback callback,
                        optional SchedulerPostTaskOptions options = {});
};