// Source: CSSOM View Module (https://www.w3.org/TR/cssom-view-1/)
dictionary ScrollIntoViewOptions : ScrollOptions {
  ScrollLogicalPosition block = "start";
  ScrollLogicalPosition inline = "nearest";
};