// Source: Service Workers Nightly (https://www.w3.org/TR/service-workers/)
[SecureContext, Exposed=(Window,Worker)]
interface ServiceWorker : EventTarget {
  readonly attribute USVString scriptURL;
  readonly attribute ServiceWorkerState state;
  undefined postMessage(any message, sequence<object> transfer);
  undefined postMessage(any message, optional StructuredSerializeOptions options = {});

  // event
  attribute EventHandler onstatechange;
};

// Source: Service Workers Nightly (https://www.w3.org/TR/service-workers/)
ServiceWorker includes AbstractWorker;