// Source: Service Workers Nightly (https://www.w3.org/TR/service-workers/)
[SecureContext, Exposed=(Window,Worker)]
interface ServiceWorkerRegistration : EventTarget {
  readonly attribute ServiceWorker? installing;
  readonly attribute ServiceWorker? waiting;
  readonly attribute ServiceWorker? active;
  [SameObject] readonly attribute NavigationPreloadManager navigationPreload;

  readonly attribute USVString scope;
  readonly attribute ServiceWorkerUpdateViaCache updateViaCache;

  [NewObject] Promise<undefined> update();
  [NewObject] Promise<boolean> unregister();

  // event
  attribute EventHandler onupdatefound;
};

// Source: Notifications API Standard (https://notifications.spec.whatwg.org/)
partial interface ServiceWorkerRegistration {
  Promise<undefined> showNotification(DOMString title, optional NotificationOptions options = {});
  Promise<sequence<Notification>> getNotifications(optional GetNotificationOptions filter = {});
};

// Source: Background Fetch (https://wicg.github.io/background-fetch/)
partial interface ServiceWorkerRegistration {
  readonly attribute BackgroundFetchManager backgroundFetch;
};

// Source: Web Background Synchronization (https://wicg.github.io/background-sync/spec/)
partial interface ServiceWorkerRegistration {
  readonly attribute SyncManager sync;
};

// Source: Content Index (https://wicg.github.io/content-index/spec/)
partial interface ServiceWorkerRegistration {
  [SameObject] readonly attribute ContentIndex index;
};

// Source: Cookie Store API (https://wicg.github.io/cookie-store/)
[Exposed=(ServiceWorker,Window)]
partial interface ServiceWorkerRegistration {
  [SameObject] readonly attribute CookieStoreManager cookies;
};

// Source: Web Periodic Background Synchronization (https://wicg.github.io/periodic-background-sync/)
[Exposed=(Window,Worker)]
partial interface ServiceWorkerRegistration {
  readonly attribute PeriodicSyncManager periodicSync;
};

// Source: Payment Handler API (https://www.w3.org/TR/payment-handler/)
partial interface ServiceWorkerRegistration {
  [SameObject] readonly attribute PaymentManager paymentManager;
};

// Source: Push API (https://www.w3.org/TR/push-api/)
[SecureContext]
partial interface ServiceWorkerRegistration {
  readonly attribute PushManager pushManager;
};