// Source: Web Speech API (https://wicg.github.io/speech-api/)
// Item in N-best list
[Exposed=Window]
interface SpeechRecognitionAlternative {
    readonly attribute DOMString transcript;
    readonly attribute float confidence;
};