// Source: DOM Standard (https://dom.spec.whatwg.org/)
dictionary StaticRangeInit {
  required Node startContainer;
  required unsigned long startOffset;
  required Node endContainer;
  required unsigned long endOffset;
};