// Source: Scalable Vector Graphics (SVG) 2 (https://www.w3.org/TR/SVG2/)
[Exposed=Window]
interface SVGAnimatedTransformList {
  [SameObject] readonly attribute SVGTransformList baseVal;
  [SameObject] readonly attribute SVGTransformList animVal;
};