// Source: Scalable Vector Graphics (SVG) 2 (https://www.w3.org/TR/SVG2/)
[Exposed=Window]
interface SVGAnimatedLength {
  [SameObject] readonly attribute SVGLength baseVal;
  [SameObject] readonly attribute SVGLength animVal;
};