// Source: Filter Effects Module Level 1 (https://www.w3.org/TR/filter-effects-1/)
[Exposed=Window]
interface SVGFETileElement : SVGElement {
  readonly attribute SVGAnimatedString in1;
};

// Source: Filter Effects Module Level 1 (https://www.w3.org/TR/filter-effects-1/)
SVGFETileElement includes SVGFilterPrimitiveStandardAttributes;