// Source: SVG Animations (https://svgwg.org/specs/animations/)
[Exposed=Window]
interface SVGMPathElement : SVGElement {
};

// Source: SVG Animations (https://svgwg.org/specs/animations/)
SVGMPathElement includes SVGURIReference;