// Source: Scalable Vector Graphics (SVG) 2 (https://www.w3.org/TR/SVG2/)
[Exposed=Window]
interface SVGPolygonElement : SVGGeometryElement {
};

// Source: Scalable Vector Graphics (SVG) 2 (https://www.w3.org/TR/SVG2/)
SVGPolygonElement includes SVGAnimatedPoints;