// Source: WebGL Specification (https://registry.khronos.org/webgl/specs/latest/1.0/)
typedef (ImageBitmap or
         ImageData or
         HTMLImageElement or
         HTMLCanvasElement or
         HTMLVideoElement or
         OffscreenCanvas or
         VideoFrame) TexImageSource;