// Source: Encoding Standard (https://encoding.spec.whatwg.org/)
[Exposed=*]
interface TextDecoder {
  constructor(optional DOMString label = "utf-8", optional TextDecoderOptions options = {});

  USVString decode(optional [AllowShared] BufferSource input, optional TextDecodeOptions options = {});
};

// Source: Encoding Standard (https://encoding.spec.whatwg.org/)
TextDecoder includes TextDecoderCommon;