// Source: Trusted Types (https://www.w3.org/TR/trusted-types/)
[Exposed=(Window,Worker)]
interface TrustedScriptURL {
  stringifier;
  USVString toJSON();
  static TrustedScriptURL fromLiteral(object templateStringsArray);
};