// Source: User-Agent Client Hints (https://wicg.github.io/ua-client-hints/)
dictionary UADataValues {
  sequence<NavigatorUABrandVersion> brands;
  boolean mobile;
  DOMString architecture;
  DOMString bitness;
  DOMString model;
  DOMString platform;
  DOMString platformVersion;
  DOMString uaFullVersion; // deprecated in favor of fullVersionList
  boolean wow64;
  sequence<NavigatorUABrandVersion> fullVersionList;
};