// Source: Media Playback Quality (https://w3c.github.io/media-playback-quality/)
[Exposed=Window]
interface VideoPlaybackQuality {
  readonly attribute DOMHighResTimeStamp creationTime;
  readonly attribute unsigned long droppedVideoFrames;
  readonly attribute unsigned long totalVideoFrames;

  // Deprecated!
  readonly attribute unsigned long corruptedVideoFrames;
};