// Source: WebGL OES_vertex_array_object Khronos Ratified Extension Specification (https://registry.khronos.org/webgl/extensions/OES_vertex_array_object/)
[Exposed=(Window,Worker), LegacyNoInterfaceObject]
interface WebGLVertexArrayObjectOES : WebGLObject {
};