// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
[Exposed=Window, SecureContext]
interface Worklet {
  [NewObject] Promise<undefined> addModule(USVString moduleURL, optional WorkletOptions options = {});
};