// Source: WebXR Anchors Module (https://immersive-web.github.io/anchors/)
[SecureContext, Exposed=Window]
interface XRAnchor {
  readonly attribute XRSpace anchorSpace;

  Promise<DOMString> requestPersistentHandle();

  undefined delete();
};