// Source: WebXR Hit Test Module (https://www.w3.org/TR/webxr-hit-test-1/)
[SecureContext, Exposed=Window]
interface XRHitTestResult {
  XRPose? getPose(XRSpace baseSpace);
};

// Source: WebXR Anchors Module (https://immersive-web.github.io/anchors/)
partial interface XRHitTestResult {
  Promise<XRAnchor> createAnchor();
};