// Source: WebXR Layers API Level 1 (https://www.w3.org/TR/webxrlayers-1/)
dictionary XRQuadLayerInit : XRLayerInit {
  XRTextureType textureType = "texture";
  XRRigidTransform? transform;
  float width = 1.0;
  float height = 1.0;
};