// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport({{ config.ffi_module_name() }})
import {{ config.ffi_module_name() }}
#endif

{% include "RustBufferTemplate.swift" %}
{% include "RustBufferHelper.swift" %}
{% include "Helpers.swift" %}

// Public interface members begin here.
{% for code in self.declaration_code() %}
{{ code }}
{%- endfor %}
{% import "macros.swift" as swift %}
