[bindings.kotlin]
omit_checksums = true
[bindings.python]
omit_checksums = true
[bindings.swift]
omit_checksums = true

[bindings.ruby.custom_types.ExternalUrl]
type_name = "URI"
imports = ["uri"]
lift = "URI.parse({})"
lower = "{}.to_s"
