[book]
authors = ["Firefox Sync Team <sync-team@mozilla.com>"]
language = "en"
multilingual = false
src = "src"
title = "The UniFFI user guide"

[output.html]
git-repository-url = "https://github.com/mozilla/uniffi-rs"

[output.html.playground]
runnable = false

[output.linkcheck]
exclude = [
    # To get this `api` directory, CI does, roughly , `cargo doc && cp -r ./target/doc ./docs/manual/src/internals/api`
    # so at the time we build the mdBook this isn't available.
    './api' # Used for rustdoc links to the source.
]
