// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

{% import "macros.cpp" as cpp %}

#ifndef mozilla_dom_{{ context.namespace()|header_name_cpp(context) }}
#define mozilla_dom_{{ context.namespace()|header_name_cpp(context) }}

#include "mozilla/dom/{{ context.namespace()|header_name_cpp(context) }}Binding.h"

namespace mozilla {
namespace dom {

class {{ context.namespace()|class_name_cpp(context) }} final {
 public:
  {{ context.namespace()|class_name_cpp(context) }}() = default;
  ~{{ context.namespace()|class_name_cpp(context) }}() = default;

  {%- for func in functions %}

  static {% match func.cpp_return_type() %}{% when Some with (type_) %}{{ type_|ret_type_cpp(context) }}{% else %}void{% endmatch %} {{ func.name()|fn_name_cpp }}(
    {%- for arg in func.cpp_arguments() %}
    {{ arg|arg_type_cpp(context) }} {{ arg.name() }}{%- if !loop.last %},{% endif %}
    {%- endfor %}
  );

  {%- endfor %}
};

}  // namespace dom
}  // namespace mozilla

#endif  // mozilla_dom_{{ context.namespace()|header_name_cpp(context) }}
