/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

mod from_ci;
mod nodes;
mod sort;
mod visit_mut;

pub use nodes::*;
pub use uniffi_meta::Radix;
pub use visit_mut::VisitMut;

// Note: the interface code is currently in a bit of a transition state. Most languages are still
// using the `ComponentInterface` to render their bindings, but we plan to switch them over to this
// system.
//
// Once we do that, we can rework the metadata code to generate a `BindingsIr` directly,
// delete a ton of the older code, and consider folding the contents of the `ir` module into
// `interface`.

/// Intermediate representation of the generated bindings for a single crate
///
/// This generated by taking the metadata from the proc-macros and adding derived info, like scaffolding functions.
/// Each bindings generator specializes [BindingsIr] for their language by mutating the nodes and adding data to the `x` fields.
/// See `<https://mozilla.github.io/uniffi-rs/latest/internals/bindings_render_pipeline.html>` for an overview of this.
#[derive(Debug, Clone)]
pub struct BindingsIr {
    pub crate_docstring: Option<String>,
    pub globals: GlobalDefinitions,
    pub checksum_checks: Vec<ChecksumCheck>,
    pub ffi_definitions: Vec<FfiDefinition>,
    pub type_definitions: Vec<TypeDefinition>,
    pub functions: Vec<Function>,
}

#[derive(Debug, Clone)]
pub struct GlobalDefinitions {
    pub ffi_rustbuffer_alloc: FfiFunctionRef,
    pub ffi_rustbuffer_reserve: FfiFunctionRef,
    pub ffi_rustbuffer_free: FfiFunctionRef,
    /// FFI function to check the contract version
    pub ffi_uniffi_contract_version: FfiFunctionRef,
    /// FFI function type for freeing a callback interface
    pub callback_interface_free_type: FfiType,
    /// Always defined String, since it's used to handle Rust call errors
    pub string_type: Type,
    pub contract_version: u32,
}

#[derive(Debug, Clone)]
pub struct ChecksumCheck {
    pub func: FfiFunctionRef,
    pub checksum: u16,
}
