namespace todolist {
};

dictionary TodoEntry {
    string text;
};

interface TodoList {
    constructor();
    void add_item(string todo);
    void add_entry(TodoEntry entry);
    void add_entries(sequence<TodoEntry> entries);
    void add_items(sequence<string> items);
    TodoEntry get_last_entry();
    sequence<TodoEntry> get_entries();
    sequence<string> get_items();
    string get_last();
};
