// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#ifndef mozilla_{{ ci.namespace() }}
#define mozilla_{{ ci.namespace() }}

#include "{{ ci.namespace()|interface_name_xpidl }}.h"

#include <functional>

#include "nsCOMPtr.h"
#include "nsIVariant.h"
#include "nsTArray.h"
#include "prnetdb.h"

#include "mozilla/Atomics.h"
#include "mozilla/Casting.h"
#include "mozilla/CheckedInt.h"
#include "mozilla/Result.h"
#include "mozilla/ResultExtensions.h"
#include "mozilla/Utf8.h"

#include "mozilla/dom/BindingDeclarations.h"
#include "mozilla/dom/Record.h"

extern "C" {

struct RustBuffer {
  int64_t mLen;
  uint8_t* mData;
};

struct RustError {
  int32_t mCode;
  char* mMessage;
};

{% for func in ci.iter_ffi_function_definitions() -%}
{%- match func.return_type() -%}
{%- when Some with (type_) %}
{{ type_|type_ffi }}
{% when None %}
void
{%- endmatch %}
{{ func.name() }}(
    {%- for arg in func.arguments() %}
    {{ arg.type_()|type_ffi }} {{ arg.name() -}}{%- if loop.last -%}{%- else -%},{%- endif -%}
    {%- endfor %}
    {%- if func.has_out_err() -%}{%- if func.arguments().len() > 0 %},{% endif %}
    RustError* out_err
    {%- endif %}
);

{% endfor -%}

}  // extern "C"

namespace mozilla {
namespace {{ ci.namespace() }} {

namespace detail {

{% include "Detail.cpp" %}

}  // namespace detail

{%- let functions = ci.iter_function_definitions() %}
{%- if !functions.is_empty() %}

class {{ ci.namespace()|class_name_cpp }} final : public {{ ci.namespace()|interface_name_xpidl }} {
  NS_DECL_THREADSAFE_ISUPPORTS
  NS_DECL_{{ ci.namespace()|interface_name_xpidl|upper }}

 public:
  {{ ci.namespace()|class_name_cpp }}() = default;
  static already_AddRefed<{{ ci.namespace()|class_name_cpp }}> GetSingleton();

 private:
  ~{{ ci.namespace()|class_name_cpp }}() = default;
};

{% endif -%}

{%- for obj in ci.iter_object_definitions() %}

class {{ obj.name()|class_name_cpp }} final : public {{ obj.name()|interface_name_xpidl }} {
  NS_DECL_THREADSAFE_ISUPPORTS
  NS_DECL_{{ obj.name()|interface_name_xpidl|upper }}

 public:
  {{ ci.namespace()|class_name_cpp }}() = default;

 private:
  ~{{ ci.namespace()|class_name_cpp }}();

  mozilla::Atomic<int64_t> mHandle;
};

{% endfor -%}

}  // namespace {{ ci.namespace() }}
}  // namespace mozilla

#endif  // mozilla_{{ ci.namespace() }}
