// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#include "mozilla/dom/{{ obj.name()|class_name_webidl }}.h"

namespace mozilla {
namespace {{ ci.namespace() }} {

}  // namespace {{ ci.namespace() }}
}  // namespace mozilla
