// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

{% import "macros.cpp" as cpp %}

#ifndef mozilla_dom_{{ namespace|class_name_webidl }}
#define mozilla_dom_{{ namespace|class_name_webidl }}

#include "mozilla/dom/{{ namespace|class_name_webidl }}Binding.h"

namespace mozilla {
namespace dom {

class {{ namespace|class_name_cpp }} final {
 public:
  {{ namespace|class_name_cpp }}() = default;
  ~{{ namespace|class_name_cpp }}() = default;

  {% for func in functions %}
  static {% call cpp::decl_return_type(func) %} {{ func.name()|fn_name_cpp }}(
      {% call cpp::decl_static_method_args(func) %}
  );
  {% endfor %}
};

}  // namespace dom
}  // namespace mozilla

#endif  // mozilla_dom_{{ namespace|class_name_webidl }}
