/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

use std::io::prelude::*;
use std::{
    env,
    collections::HashMap,
    convert::TryFrom, convert::TryInto,
    fs::File,
    iter::IntoIterator,
    fmt::Display,
    path::{Path, PathBuf},
};

use anyhow::bail;
use anyhow::Result;
use anyhow::Error;
use askama::Template;

use super::interface::*;

#[derive(Template)]
#[template(ext="rs", escape="none", source=r#"
// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

use anyhow::{bail, Result, Error};

#[no_mangle]
pub extern "C" fn {{ ci.ffi_bytebuffer_alloc().name() }}(size: u32) -> ffi_support::ByteBuffer {
    ffi_support::ByteBuffer::new_with_size(size.max(0) as usize)
}

ffi_support::define_bytebuffer_destructor!({{ ci.ffi_bytebuffer_free().name() }});

{% for e in ci.iter_enum_definitions() %}

    enum {{ e.name() }} {
    {%- for value in e.values() %}
        {{ value }} = {{ loop.index -}},
    {%- endfor %}
    }

    unsafe impl uniffi::support::ViaFfi for {{ e.name() }} {
        type Value = u32;
        fn into_ffi_value(self) -> Self::Value {
            self as Self::Value
        }
        fn try_from_ffi_value(v: Self::Value) -> Result<Self> {
            Ok(match v {
                {%- for value in e.values() %}
                {{ loop.index }} => {{ e.name() }}::{{ value }},
                {%- endfor %}
                _ => bail!("Invalid {{ e.name() }} enum value: {}", v),
            })
        }
    }

{% endfor %}

{% for rec in ci.iter_record_definitions() %}
    #[derive(Debug, Clone)]
    pub struct {{ rec.name() }} {
      {%- for field in rec.fields() %}
        pub {{ field.name() }}: {{ field.type_()|decl_rs -}},
      {%- endfor %}
    }

    impl uniffi::support::Lowerable for {{ rec.name() }} {
        fn lower_into<B: uniffi::support::BufMut>(&self, buf: &mut B) {
          {%- for field in rec.fields() %}
            uniffi::support::Lowerable::lower_into(&self.{{ field.name() }}, buf);
          {%- endfor %}
        }
    }

    impl uniffi::support::Liftable for {{ rec.name() }} {
        fn try_lift_from<B: uniffi::support::Buf>(buf: &mut B) -> Result<Self, Error> {
          Ok(Self {
            {%- for field in rec.fields() %}
                {{ field.name() }}: <{{ field.type_()|decl_rs }} as uniffi::support::Liftable>::try_lift_from(buf)?,
            {%- endfor %}
          })
        }
    }

    impl uniffi::support::ViaFfiUsingByteBuffer for {{ rec.name() }} {}
{% endfor %}

{%- for func in ci.iter_function_definitions() %}
    {%- match func.ffi_func().return_type() -%}
    {%- when Some with (return_type) %}

        #[no_mangle]
        pub extern "C" fn {{ func.ffi_func().name() }}(
            {%- for arg in func.ffi_func().arguments() %}
            {{ arg.name() }}: {{ arg.type_()|decl_c }},
            {%- endfor %}
        ) -> {{ return_type|decl_c }} {
            log::debug!("{{ func.ffi_func().name() }}");
            let _retval: {{ return_type|decl_rs }} = {{ func.name() }}(
                {%- for arg in func.arguments() %}
                {{ arg.name()|lift_rs(arg.type_()) }},
                {%- endfor %}
            );
            {{ "_retval"|lower_rs(return_type) }}
        }

    {% when None %}

        #[no_mangle]
        pub extern "C" fn {{ func.ffi_func().name() }}(
            {%- for arg in func.ffi_func().arguments() %}
            {{ arg.name() }}: {{ arg.type_()|decl_c }},
            {%- endfor %}
        ) {
            log::debug!("{{ func.ffi_func().name() }}");
            {{ func.name() }}(
                {%- for arg in func.arguments() %}
                {{ arg.name()|lift_rs(arg.type_()) }},
                {%- endfor %}
            );
        }

    {% endmatch %}
{% endfor -%}

{% for obj in ci.iter_object_definitions() %}

lazy_static::lazy_static! {
  static ref UNIFFI_HANDLE_MAP_{{ obj.name() }}: ffi_support::ConcurrentHandleMap<{{ obj.name() }}> = ffi_support::ConcurrentHandleMap::new();
}

// XXX TODO: destructors.
// These will need to be defined as another FFI function on the Object struct, and included automatically
// in the set of all FFI functions for use by the bindings.
// define_handle_map_deleter!(UNIFFI_HANDLE_MAP_{{ obj.name() }}, {{ obj.name() }}_free);


{%- for cons in obj.constructors() %}
    #[no_mangle]
    pub extern "C" fn {{ cons.ffi_func().name() }}(
        {%- for arg in cons.ffi_func().arguments() %}
        {{ arg.name() }}: {{ arg.type_()|decl_c }},
        {%- endfor %}
    ) -> u64 {
        log::debug!("{{ cons.ffi_func().name() }}");
        let mut err: ffi_support::ExternError = Default::default(); // XXX TODO: error handling!
        let _handle = UNIFFI_HANDLE_MAP_{{ obj.name() }}.insert_with_output(&mut err, || {
            let obj = {{ obj.name() }}::{{ cons.name() }}(
                {%- for arg in cons.arguments() %}
                {{ arg.name()|lift_rs(arg.type_()) }},
                {%- endfor %}
            );
            obj
        });
        _handle
    }
{% endfor %}

{%- for meth in obj.methods() %}
    #[no_mangle]
    pub extern "C" fn {{ meth.ffi_func().name() }}(
        {%- for arg in meth.ffi_func().arguments() %}
        {{ arg.name() }}: {{ arg.type_()|decl_c }},
        {%- endfor %}
    ) -> {% match meth.ffi_func().return_type() %}{% when Some with (return_type) %}{{ return_type|decl_c }}{% else %}(){% endmatch %} {
        log::debug!("{{ meth.ffi_func().name() }}");
        let mut err: ffi_support::ExternError = Default::default(); // XXX TODO: error handling!
        UNIFFI_HANDLE_MAP_{{ obj.name() }}.call_with_output_mut(&mut err, {{ meth.first_argument().name() }}, |obj| {
            let _retval = {{ obj.name() }}::{{ meth.name() }}(
                obj,
                {%- for arg in meth.arguments() %}
                {{ arg.name()|lift_rs(arg.type_()) }},
                {%- endfor %}
            );
            {% match meth.return_type() %}{% when Some with (return_type) %}{{ "_retval"|lower_rs(return_type) }}{% else %}{% endmatch %}
        })
    }
{% endfor %}

{% endfor %}
"#)]
pub struct RustScaffolding<'a> {
  ci: &'a ComponentInterface,
}
impl<'a> RustScaffolding<'a> {
    pub fn new(ci: &'a ComponentInterface) -> Self {
        Self { ci }
    }
}

mod filters {
    use std::fmt;
    use super::*;

    pub fn decl_rs(type_: &TypeReference) -> Result<String, askama::Error> {
        Ok(match type_ {
            // These can be passed directly over the FFI without conversion.
            TypeReference::U32 => "u32".to_string(),
            TypeReference::U64 => "u64".to_string(),
            TypeReference::Float => "f32".to_string(),
            TypeReference::Double => "f64".to_string(),
            TypeReference::Boolean => "u8".to_string(),
            // These types need conversion, and will require special handling below
            // when lifting/lowering.
            TypeReference::String => "&str".to_string(),
            TypeReference::Enum(name) => name.clone(),
            TypeReference::Record(name) => name.clone(),
            TypeReference::Optional(t) => format!("Option<{}>", decl_rs(t)?),
            _ => panic!("[TODO: decl_rs({:?})]", type_),
        })
    }

    pub fn decl_c(type_: &TypeReference) -> Result<String, askama::Error> {
        Ok(match type_ {
            TypeReference::String => "FfiStr<'_>".to_string(),
            TypeReference::Enum(_) => "u32".to_string(),
            TypeReference::Record(_) => "ffi_support::ByteBuffer".to_string(),
            TypeReference::Optional(_) => "ffi_support::ByteBuffer".to_string(),
            TypeReference::Object(_) => "u64".to_string(),
            _ => decl_rs(type_)?
        })
    }

    pub fn lower_rs(nm: &dyn fmt::Display, type_: &TypeReference) -> Result<String, askama::Error> {
        // By explicitly naming the type here, we help the rust compiler to type-check the user-provided
        // implementations of the functions that we're wrapping (and also to type-check our generated code).
        Ok(format!("<{} as uniffi::support::ViaFfi>::into_ffi_value({})", decl_rs(type_)?, nm))
    }

    pub fn lift_rs( nm: &dyn fmt::Display, type_: &TypeReference) -> Result<String, askama::Error> {
        // By explicitly naming the type here, we help the rust compiler to type-check the user-provided
        // implementations of the functions that we're wrapping (and also to type-check our generated code).
        Ok(format!("<{} as uniffi::support::ViaFfi>::try_from_ffi_value({}).unwrap()", decl_rs(type_)?, nm)) // Error handling later...
    }
}